---
- name: Install apache & modules
  apt: name=apache2 state=present
  with_items:
    - apache2
    - libapache2-mod-php7.0

- name: Enabled mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
    - reload apache

- name: Create websites directory
  file: 
    path=/vagrant/sites 
    state=directory

- name: Use local template for virtualhost on webserver
  template:
    src=vhost.conf.j2
    dest=/etc/apache2/sites-available/localroot.conf
  notify:
    - reload apache

- name: Remove default apache virtualhost
  file:
    path=/etc/apache2/sites-enabled/000-default.conf
    state=absent
  notify:
    - reload apache

- name: Enable our virtualhost
  file:
    src=/etc/apache2/sites-available/localroot.conf
    dest=/etc/apache2/sites-enabled/localroot.conf
    state=link
  notify:
    - reload apache