---
- name: Install apache & modules
  apt: name={{item}} state=present
  with_items:
    - apache2
    - libapache2-mod-php7.0

- name: Enabled mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
    - reload apache

- name: Create websites directory
  file: 
    path=/vagrant/sites 
    state=directory

- name: Add the user 'vagrant' to the group 'www-data'
  user: 
    name: vagrant
    groups: www-data
    append: yes

- name: Use local template for virtualhost on webserver
  template:
    src=vhost.conf.j2
    dest=/etc/apache2/sites-available/{{item.servername}}.conf
  with_items:
    - "{{apache_vhosts}}"
  notify:
    - reload apache

- name: Remove default apache virtualhost
  file:
    path=/etc/apache2/sites-enabled/000-default.conf
    state=absent
  notify:
    - reload apache

- name: Enable virtualhosts
  file:
    src=/etc/apache2/sites-available/{{item.servername}}.conf
    dest=/etc/apache2/sites-enabled/{{item.servername}}.conf
    state=link
  with_items:
    - "{{apache_vhosts}}"
  notify:
    - reload apache

- name: Add servernames in hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "127.0.0.1 {{item.servername}}"
  with_items:
    - "{{apache_vhosts}}"
