---
- name: install mysql
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - mysql-client
    - python3-dev
    - python-mysqldb
    - libmysqlclient-dev
  notify:
    - restart mysql

- name: Install pip
  apt: name=python3-pip state=present

- name: Install mysqlclient with pip
  pip: name=mysqlclient

- name: Create user for mysql with all right
  mysql_user:
    name={{ mysql_username }}
    password={{ mysql_password }}
    priv='*.*:ALL,GRANT'
    state=present
  notify:
    - restart mysql

- name: Import database
  mysql_db:
    state: import
    name: "{{ item.filename }}"
    target: /vagrant/sites/{{item.dirname}}/{{ item.filename }}.sql
  with_items:
    - "{{databases}}"
