---
- name: install mysql
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - mysql-client
    - python3-dev
  notify:
    - reload mysql

- name: Create user for mysql with all right
  mysql_user:
    name="{{ mysql_username }}"
    password="{{ mysql_password }}"
    priv='*.*:ALL,GRANT'
    state=present
  notify:
    - reload mysql