---

- hosts: all
  sudo: true
  handlers:
  - name: reload apache
    service: name=apache2 state=reloaded
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes
  roles:
    - webserver
    - database